"""empty message

Revision ID: 6cb884345a2c
Revises: 33ecc87f17c3
Create Date: 2021-02-11 20:56:51.849855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb884345a2c'
down_revision = '33ecc87f17c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
